### ISSUE TITLE
MeshShape can't be child of CompoundShape

### ISSUE THREAD

**Issue by mbrazell** [chandlerprall/GoblinPhysics#44]
Adding a MeshShape as a child shape to a CompoundShape causes "Uncaught TypeError: undefined is not a function", which references line 3578 of goblin.js:

use_contact = contact.object_a.emit( 'newContact', contact.object_b, contact );

"emit" is undefined.

I encountered this issue in my own code, and then re-created it in the mesh-shape-statue demo by adding the MeshShape object as a child to a CompoundShape before adding it to the rigid body:

// shape is the MeshShape of the statue
var compoundShape = new Goblin.CompoundShape();
compoundShape.addChildShape(shape, new Goblin.Vector3(), new Goblin.Quaternion());
 
mesh.goblin = new Goblin.RigidBody( compoundShape, 0 );

**Comment by chandlerprall** [comment]
Thanks for reporting, will get it looked at soon.

**Comment by chandlerprall** [comment]
This should now be fixed on the 0.9 branch

**Comment by mbrazell** [comment]
Thanks for the update!
