### ISSUE TITLE
MeshShapes don't collide with other MeshShapes

### ISSUE THREAD

**Issue by mbrazell** [chandlerprall/GoblinPhysics#45]
It appears that MeshShapes only respond to collision with simple shapes, such as boxes and spheres.  I made a second statue in the mesh-shape-statue demo; I placed it above the first, and added mass to each, so that they would respond to gravity.  The second (higher) mesh shape passes directly through the first with no reaction.

**Comment by chandlerprall** [comment]
This is a current limitation of the engine. MeshShape/MeshShape collisions are close to working but not quite there.

**Comment by mbrazell** [comment]
I've tested several javascript physics engines for 3D, and hope to be able to use Goblin when this issue is resolved!  Thank you.

**Comment by chandlerprall** [comment]
The initial code for this is on the 0.9 branch if you want to take a look. I've also posted [an example](http://www.goblinphysics.com/examples/mesh-mesh.html)

**Comment by mbrazell** [comment]
Thank you!  I will check it out.
