### ISSUE TITLE
Export MeshShape/Compound Shape from Blender?

### ISSUE THREAD

**Issue by belohlavek** [chandlerprall/GoblinPhysics#58]
Hello, I'm trying to get started using 3D with three.js and I'm having a hard time understanding how to easily edit collision shapes in blender and export them to a JavaScript Physics engine.

How do I export a mesh as a MeshShape in Blender?
Or, if I'm not pointing in the right direction: how do I easily modify MeshShapes for Goblin Physics (or Physijs)? Do I need to create my own editor?

Thank you for reading.

**Comment by chandlerprall** [comment]
You can re-use the 3D geometry you generate for Three.js. Take a look at the code for [mesh-shape example](https://github.com/chandlerprall/GoblinPhysics/blob/master/examples/mesh-shape.html#L32) which does just that.
