### ISSUE TITLE
I was wondering if heightmaps are supported?

### ISSUE THREAD

**Issue by fossephate** [chandlerprall/GoblinPhysics#65]
I couldn't find an example of a height map or modification of a plane in any of the examples, is there a way to use them?
I'm considering switching my project over to goblin physics from cannon.js, but I need the ability to create terrain via heightmap. I realize I could build the physics object as a concave mesh, but that seems like it would be bad performance wise.

I'm not sure if this is the correct place to post this, but I couldn't find anywhere else to post it.

**Comment by chandlerprall** [comment]
No worries, this is a fine area to ask.

Heightmaps are great when you have a very large terrain and don't want to store all of the faces' parameters in memory at once. The trade off is you incur more processing time when detecting collisions.

The other capability heightmaps give you is the ability to change the vertices' heights after creating the object. If you don't need either of these (avoid memory use or dynamic heights) the concave mesh should do fine.

**Comment by SET001** [comment]
@chandlerprall, so if there are something like `Physijs.HeightfieldMesh` in GoblinPhysics?
