### ISSUE TITLE
Three.js example?

### ISSUE THREAD

**Issue by trusktr** [chandlerprall/GoblinPhysics#68]
Would you mind making a small example of using Goblin with Three.js?

**Comment by chandlerprall** [comment]
All of the [examples](https://github.com/chandlerprall/GoblinPhysics/tree/master/examples) - except Raytracer - use Three.js

**Comment by trusktr** [comment]
Oops, I missed the exampleUtils. I was looking at the html files and thought that that was showing the Goblin API and that it used its own rendering behind the scenes.

Thanks!

I'm looking at various physics engines, and I'm noticing a pattern: the end user has to create two parallel trees. For example, in your exampleUtils, you create the Three.js scene graph tree, and on every node you attach the goblin body which composes the second Goblin world tree. Then, the end user has to make sure to sync positions from the physics tree to the visual tree.

I myself am making a [3D library](https://github.com/trusktr/infamous) (planning to add WebGL soon, but currently just CSS3D). I'm debating on how I want to implement physics: should the end user create a single tree with physics integrated, which may be easier to reason about and work with, or should I make the end user make two trees which is more complicated and more work.

One of my goals is to make the API as easy as possible to use.

**Comment by chandlerprall** [comment]
Your observation about the two trees + syncing is correct. I have another project called Physijs which adds physics to Three.js as a plugin, the [v2 branch](https://github.com/chandlerprall/Physijs/tree/2.0) uses Goblin - this is actually why I started Goblin in the first place.
